In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

In [2]:
data = load_iris()
df = pd.DataFrame(data=data.data, columns=data.feature_names)
df['target'] = data.target

In [3]:
df.iloc[5:10, 0] = np.nan
print("Missing data in the dataset:\n", df.isnull().sum())

Missing data in the dataset:
 sepal length (cm)    5
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64


In [4]:
df.fillna(df.mean(), inplace=True)
print("\nMissing data after filling with mean:\n", df.isnull().sum())


Missing data after filling with mean:
 sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64


In [5]:
X = df.drop('target', axis=1)  # Features
y = df['target']  # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
print("\nScaled Training Data (first 5 rows):\n", X_train_scaled[:5])
print("\nScaled Test Data (first 5 rows):\n", X_test_scaled[:5])


Scaled Training Data (first 5 rows):
 [[-1.55865245  1.20365799 -1.56253475 -1.31260282]
 [-0.17976665  2.99237573 -1.27600637 -1.04563275]
 [ 1.07376589  0.08570939  0.38585821  0.28921757]
 [-1.30794594  0.75647855 -1.2187007  -1.31260282]
 [-1.80935896  0.30929911 -1.39061772 -1.31260282]]

Scaled Test Data (first 5 rows):
 [[ 0.32164637 -0.58505976  0.55777524  0.02224751]
 [-0.17976665  1.65083742 -1.16139502 -1.17911778]
 [ 2.32729844 -1.0322392   1.8185001   1.49058286]
 [ 0.19629311 -0.36147005  0.44316389  0.4227026 ]
 [ 1.19911915 -0.58505976  0.61508092  0.28921757]]
